---
title: "project_milestone_4"
output: html_document
date: "2023-11-16"
---

```{r}
library(tidyverse)
library(dplyr)
library(plotly)  
library(kableExtra)
```


###Joining Datasets
```{r}

flu_vax <- flu %>%
  full_join(vax, by = c("county","demographic_value","demographic_category","quarter"))

```
###Visualizations

**Table**: Rates of Severe Flu and COVID Vaccination by Demographic Group

```{r}
flu_vax_rate_by_demo <- flu_vax %>%
  group_by(demographic_category,demographic_value) %>%
  summarise(new_severe = sum(new_severe, na.rm = TRUE),
            total_partial_vaccinated = sum(total_partial_vaccinated, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(flu_pop_demo_state, by = "demographic_value") %>%
  left_join(vax_pop_demo_state, by = "demographic_value") %>%
  mutate(rate_severe = round((new_severe/pop.x)*1000,2),
         rate_partial_vaccinated = round((total_partial_vaccinated/pop.y)*1000,2)) %>%
  select(demographic_value, rate_severe, rate_partial_vaccinated) %>%
  drop_na()

flu_vax_rate_by_demo <- flu_vax %>%
  group_by(demographic_category,demographic_value) %>%
  summarise(new_severe = sum(new_severe, na.rm = TRUE),
            total_partial_vaccinated = sum(total_partial_vaccinated, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(flu_pop_demo_state, by = "demographic_value") %>%
  left_join(vax_pop_demo_state, by = "demographic_value") %>%
  mutate(rate_severe = round((new_severe/pop.x)*1000,2),
         rate_partial_vaccinated = round((total_partial_vaccinated/pop.y)*1000,2)) %>%
  select(demographic_value, rate_severe, rate_partial_vaccinated) %>%
  drop_na()

kable(flu_vax_rate_by_demo,longtable = TRUE, booktabs = TRUE, col.names = c("Demographic Group", "Severe Flu", "COVID Vaccination"), caption = "Rates of Severe Flu and COVID Vaccination by Demographic Group, California") %>%
  kable_styling(full_width = FALSE) %>%
  kable_styling(position = "left") %>%
  kable_styling(font_size = 10) %>%
  add_header_above(c(" "=1,"Rate per 1,000 population"=2)) %>%
  pack_rows("Age Group",1,4)%>%
  pack_rows("Gender",5,6) %>%
  pack_rows("Race/Ethnicity",7,13) %>%
  collapse_rows(columns = 1, valign = "top") %>%
  # add_footnote("Rates are per 1,000 population", notation = "none") %>%
  add_footnote("Based on diagnosis date from 9/24/2022 - 6/10/2023", notation = "none")
```

Interpretation: 


```{r}

flu_vax_race <- full_join(flu_rate_by_race, vax_rate_by_race, by = "demographic_value")
# Splitting the plotting area into two columns
par(mfrow = c(1, 2), mar = c(5, 4, 4, 2))

# Plot for 'severe flu'
barplot(flu_vax_race$rate_severe, names.arg = flu_vax_race$demographic_value, 
        col = "blue", main = "Severe Flu", ylab = "Rate of Severe Flu", las = 2)

# Plot for 'one dose' - adjust the margins to align with the first plot
par(mar = c(5, 2, 4, 4))
barplot(flu_vax_race$rate_cum_one_dose, names.arg = flu_vax_race$demographic_value, 
        col = "red", main = "One Dose", ylab = "Rate of One Dose", las = 2)

# Resetting graphical parameters to default
par(mfrow = c(1, 1), mar = c(5, 4, 4, 2))

```
```{r}
flu_vax_quarter <- inner_join (vax_rate_by_quarter,flu_rate_by_quarter, by ="quarter")


plot_ly(
  flu_vax_quarter,
  x = ~quarter,
  y = ~rate_total_partial,
  name = "Partial COVID Vaccination",
  type = "scatter",
  mode = "lines+markers",
  marker = list(color = "darkcyan")
) %>%
  add_trace(
    x = ~quarter,
    y = ~rate_infections,
    name = "Flu Diagnosed",
    type = "scatter",
    mode = "lines",
    line = list(color = "darkslateblue")
  ) %>%
  layout(
    title = "Rates for Partially COVID Vaccinated and Newly Flu Diagnosed by Quarter in California, 2022-2023",
    yaxis = list(title = "Rate per 1,000"),
    xaxis = list(title = "Quarters"),
    plot_bgcolor="white"
  )


plot_ly(flu_vax_quarter, x = ~quarter, y = ~rate_total_partial, type = "bar", name = "Partial COVID Vaccination", marker = list(color = "darkcyan")) %>%
  add_trace(x = ~quarter, y = ~rate_infections, type = "bar", name = "Flu Diagnosed", marker = list(color = "darkslateblue")) %>%
  layout(
    title = "Rates for Partially COVID Vaccinated and Newly Flu Diagnosed by Quarter in California, 2022-2023",
    yaxis = list(title = "Rate per 1,000"),
    xaxis = list(title = "Quarters"),
    plot_bgcolor = "white"
  )

library(ggplot2)
ggplot(flu_vax_quarter, aes(x = quarter)) +
  geom_bar(aes(y = rate_total_partial, fill = "Partial COVID Vaccination"), stat = "identity") +
  geom_bar(aes(y = rate_infections, fill = "Flu Diagnosed"), stat = "identity") +
  labs(
    title = "Rates for Partially COVID Vaccinated and Newly Flu Diagnosed by Quarter in California, 2022-2023",
    y = "Rate per 1,000",
    x = "Quarters"
  ) +
  scale_fill_manual(values = c("darkcyan", "darkslateblue")) +
  theme_minimal()
```