---
title: "project_milestone_3"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import data

Set packages and import data

```{r}
library(tidyverse)
library(dplyr)

source_vax_CA <- read.csv("~/PHW251_group_project/data/ca_vax_rates_quarter.csv")
source_flu_LA <- read.csv("~/PHW251_group_project/data/sim_flu_LACounty_pop.csv")
source_flu_CA <- read.csv("~/PHW251_group_project/data/sim_flu_CA.csv")

str(source_flu_CA)
#str(source_flu_LA)
#str(source_vax_CA)

unique(source_flu_CA$race_ethnicity)
unique(source_flu_LA$RACE_ETH)
```


## Stack flu data sets

Clean CA flu data

```{r}
flu_CA <- source_flu_CA %>%
  mutate(county = str_replace(county,"County",""),
         race_ethnicity = case_when(race_ethnicity == "1" ~ "White, Non-Hispanic",
                                    race_ethnicity == "2" ~ "Black, Non-Hispanic",
                                    race_ethnicity == "3" ~ "American Indian or Alaska Native, Non-Hispanic",
                                    race_ethnicity == "4" ~ "Asian, Non-Hispanic",
                                    race_ethnicity == "5" ~ "Native Hawaiian or Pacific Islander, Non-Hispanic",
                                    race_ethnicity == "6" ~ "Multiracial (two or more of above races), Non-Hispanic",
                                    race_ethnicity == "7" ~ "Hispanic (any race)",
                                    race_ethnicity == "9" ~ "Unknown"),
                                    #TRUE ~ "Unknown"
         report_date = as.Date(report_date, format = "%Y-%m-%d"),
         dt_diagnosis = as.Date(dt_diagnosis, format = "%Y-%m-%d"))



# do we need to do something with time_int which is presented as int? Maybe as.Date
```

Clean LA flu data to match CA flu data

```{r}

flu_LA <- source_flu_LA %>%
  rename(new_infections = DX_NEW,
         new_recovered = RECOVERED_NEW,
         count_susceptible = SUSCEPTIBLE,
         current_infected = INFECTED_CURRENT,
         cumulative_infected = INFECTED_CUMULATIVE,
         cumulative_recovered = RECOVERED_CUMULATIVE,
         new_severe = SEVERE_NEW,
         cumulative_severe = SEVERE_CUMULATIVE,
         age_cat = AGE_CATEGORY,
         sex = SEX,
         race_ethnicity = RACE_ETH,
         report_date = DT_REPORT,
         dt_diagnosis = DT_DX,
         pop = POPULATION) %>%
  mutate(county = "Los Angeles",
         dt_diagnosis = as.Date(dt_diagnosis, format = "%d%b%Y"),
         time_int = NA_character_,
         new_unrecovered = NA_real_,
         cumulative_unrecovered = NA_real_) %>%
  select(county,
         time_int,
         new_infections,
         new_recovered,
         count_susceptible,
         current_infected,
         cumulative_infected,
         cumulative_recovered,
         new_unrecovered,
         cumulative_unrecovered,
         new_severe,
         cumulative_severe,
         age_cat,
         sex,
         race_ethnicity,
         report_date,
         dt_diagnosis,
         pop)

```

Stack CA and LA flu data, and restructure to match vax data

```{r}

flu_CA_LA <- rbind(flu_CA, flu_LA)

colSums(is.na(flu_CA_LA))

#restructure flu data so one demographic variable per row. Done once for new_infections and again for pop

 flu_age <- flu_CA_LA %>%
   group_by(county,age_cat,dt_diagnosis) %>%
   summarise(new_infections = sum(new_infections),
             new_severe = sum(new_severe)) %>%
   ungroup()  %>%
   mutate(demographic_category = "Age Group") %>%
   rename(demographic_value = age_cat)

flu_sex <- flu_CA_LA %>%
   group_by(county,sex,dt_diagnosis) %>%
   summarise(new_infections = sum(new_infections),
             new_severe = sum(new_severe)) %>%
   ungroup() %>%
   mutate(demographic_category = "Gender") %>%
   rename(demographic_value = sex)

 flu_race <- flu_CA_LA %>%
   group_by(county,race_ethnicity,dt_diagnosis) %>%
   summarise(new_infections = sum(new_infections),
             new_severe = sum(new_severe)) %>%
   ungroup() %>%
   mutate(demographic_category = "Race/Ethnicity") %>%
   rename(demographic_value = race_ethnicity)

flu_cases <- rbind(flu_age, flu_sex, flu_race)

# var <- c("age_cat", "sex", "race_ethnicity")
# value <- c("Age Group", "Gender", "Race/Ethnicity")
#
# for (i in 1:length(var)) {
#   flu_var[i] <- flu_CA_LA %>%
#     group_by(county,var[i],dt_diagnosis) %>%
#     summarise(new_infections = sum(new_infections)) %>%
#     ungroup() %>%
#     mutate(demographic_category = value[i]) %>%
#     rename(demographic_value = var[i])
# }

# restructure flu pop column so only one demographic variable per column

 pop_flu_age <- flu_CA_LA %>%
   distinct(county,age_cat,sex,race_ethnicity,pop) %>%
   group_by(county,age_cat) %>%
   summarise(pop = sum(pop)) %>%
   ungroup() %>%
   rename(demographic_value = age_cat) %>%
   mutate(demographic_category = "Age Group")

 pop_flu_sex <- flu_CA_LA %>%
   distinct(county,age_cat,sex,race_ethnicity,pop) %>%
   group_by(county,sex) %>%
   summarise(pop = sum(pop)) %>%
   ungroup() %>%
   rename(demographic_value = sex) %>%
   mutate(demographic_category = "Gender")

 pop_flu_race <- flu_CA_LA %>%
   distinct(county,age_cat,sex,race_ethnicity,pop) %>%
   group_by(county,race_ethnicity) %>%
   summarise(pop = sum(pop)) %>%
   ungroup() %>%
   rename(demographic_value = race_ethnicity) %>%
   mutate(demographic_category = "Race/Ethnicity")

 flu_pop <- rbind(pop_flu_age, pop_flu_sex, pop_flu_race)

# join both new_infection and pop

 flu <- flu_cases %>%
   full_join(flu_pop, by = c("county","demographic_value","demographic_category")) %>%
   mutate(month = floor_date(dt_diagnosis,"week"))

```

## Rework COVID data

```{r}

vax <- source_vax_CA %>%
  rename_with(~ tolower(gsub(".","_",.x,fixed=TRUE))) %>%
  rename(pop = estimated_population,
         county = county_name) %>%
  mutate(dt_admin = as.Date(dt_admin, format = "%Y-%m-%d"),
    demographic_value = case_when(demographic_value == "Under 5" ~ "0-17",
                                 demographic_value == "5-11" ~ "0-17",
                                 demographic_value == "12-17" ~ "0-17",
                                 demographic_value == "American Indian or Alaska Native" ~ "American Indian or Alaska Native, Non-Hispanic",
                                 demographic_value == "Asian" ~ "Asian, Non-Hispanic",
                                 demographic_value == "Black or African American" ~ "Black, Non-Hispanic",
                                 demographic_value == "Latino" ~ "Hispanic (any race)",
                                 demographic_value == "Multiracial" ~ "Multiracial (two or more of above races), Non-Hispanic",
                                 demographic_value == "Native Hawaiian or Other Pacific Islander" ~ "Native Hawaiian or Pacific Islander, Non-Hispanic",
                                 demographic_value == "White" ~ "White, Non-Hispanic",
                              #  demographic_value == "Other Race" ~ "Unknown",
                              #  demographic_value == "Unknown/undifferentiated" ~ "Unknown gender", or as NA since we don't have such data in flu and drop it?
                                 TRUE ~ demographic_value)) %>%
  group_by(county,demographic_category,demographic_value,dt_admin) %>%
  summarise(pop=sum(pop),
            total_partial_vaccinated = sum(total_partial_vaccinated),
            cumulative_fully_vaccinated = sum(cumulative_fully_vaccinated),
            cumulative_at_least_one_dose = sum(cumulative_at_least_one_dose),
            cumulative_up_to_date_vax = sum(cumulative_up_to_date_vax)) %>%
  ungroup()
#  pivot_wider(names_from=demographic_category, values_from=demographic_value)


unique(flu_CA_LA$age_cat)
unique(vax$demographic_category)
unique(source_vax_CA$Demographic.Value)


```

Notes from Will:  It would need to be COVID vax rates affect flu disease rates, since there's nothing in the datasets measures flu vax rates.